# Generated by Django 5.2 on 2025-04-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
